name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ github.token }}"

      - name: Create Empty Commit on Behalf of the Nexus Solutions Bot
        run: |
          git config --global user.email "nexus.solutions601@gmail.com"
          git config --global user.name "devs-nexus"
          git commit --allow-empty -m "$(git log -1 --pretty=%B)"

      - name: Push Empty Commit to Main Branch
        run: |
          git push origin main
